name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPOSITORY_API: douglasg96/kantox-auxiliary-api
  KUBE_NAMESPACE: auxiliary-service-prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin ${{ env.DOCKER_REGISTRY }}

      - name: Build and push API Docker image
        run: |
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY_API }}:latest .
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY_API }}:latest

  deploywithargocd:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Clone kantox-k8s repository
        run: |
          git clone https://github.com/douglasg96/kantox-k8s.git
          cd kantox-k8s/auxiliary-api
          git config --global user.name "GitHub Actions"
          git config --global user.email "drg96@gmail.com"
  
      - name: Update ConfigMap version
        run: |
          # Extract the current version
          CURRENT_VERSION=$(cat kantox-k8s/auxiliary-api/configmap.yaml | grep AUXILIARY_SERVICE_VERSION | awk '{print $2}' | tr -d '"')
          
          # Increment the patch version
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print $1"."$2"."$3+1}')
          
          # Update the ConfigMap with the new version
          sed -i "s|AUXILIARY_SERVICE_VERSION:.*|AUXILIARY_SERVICE_VERSION: \"$NEW_VERSION\"|g" kantox-k8s/auxiliary-api/configmap.yaml
          
          # Print the new version for debugging
          echo "Updated AUXILIARY_SERVICE_VERSION to $NEW_VERSION"

      - name: Commit and push changes
        run: |
          cd kantox-k8s/auxiliary-api
          git add configmap.yaml
          git commit -m "Update AUXILIARY_SERVICE_VERSION to $NEW_VERSION"
          git push https://${{ secrets.GH_TOKEN }}@github.com/douglasg96/kantox-k8s.git HEAD:main